jms_serializer:
  metadata:
    directories:
      KnpPaginatorBundle:
        namespace_prefix: "Knp\\Bundle\\PaginatorBundle"
        path: "%kernel.root_dir%/KnpPaginatorBundle/Resources/config/serializer"